const CATEGORIES = [
  { id:'image', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>`, name:'Images', formats:[
    {ext:'JPEG',name:'Joint Photographic Experts Group'},{ext:'JPG',name:'JPEG Image'},{ext:'PNG',name:'Portable Network Graphics'},
    {ext:'WEBP',name:'Web Picture Format'},{ext:'GIF',name:'Graphics Interchange Format'},{ext:'BMP',name:'Bitmap Image'},
    {ext:'TIFF',name:'Tagged Image File Format'},{ext:'TIF',name:'Tagged Image File'},{ext:'SVG',name:'Scalable Vector Graphics'},
    {ext:'AVIF',name:'AV1 Image Format'},{ext:'HEIC',name:'High Efficiency Image Container'},{ext:'HEIF',name:'High Efficiency Image Format'},
    {ext:'ICO',name:'Windows Icon'},{ext:'CUR',name:'Windows Cursor'},{ext:'PSD',name:'Photoshop Document'},
    {ext:'PSB',name:'Photoshop Large Document'},{ext:'AI',name:'Adobe Illustrator'},{ext:'EPS',name:'Encapsulated PostScript'},
    {ext:'RAW',name:'Raw Image Data'},{ext:'CR2',name:'Canon Raw v2'},{ext:'CR3',name:'Canon Raw v3'},
    {ext:'NEF',name:'Nikon Electronic Format'},{ext:'ARW',name:'Sony Alpha Raw'},{ext:'ORF',name:'Olympus Raw Format'},
    {ext:'RAF',name:'Fujifilm Raw'},{ext:'DNG',name:'Digital Negative'},{ext:'RW2',name:'Panasonic Raw'},
    {ext:'SRW',name:'Samsung Raw'},{ext:'NRW',name:'Nikon Raw (compact)'},{ext:'XCF',name:'GIMP Native Format'},
    {ext:'PCX',name:'PC Paintbrush'},{ext:'TGA',name:'Truevision TARGA'},{ext:'PPM',name:'Portable Pixmap'},
    {ext:'PGM',name:'Portable Graymap'},{ext:'PBM',name:'Portable Bitmap'},{ext:'XBM',name:'X11 Bitmap'},
    {ext:'XPM',name:'X11 Pixmap'},{ext:'JFIF',name:'JPEG File Interchange Format'},{ext:'APNG',name:'Animated PNG'},
    {ext:'JXL',name:'JPEG XL'},{ext:'QOI',name:'Quite OK Image Format'},{ext:'JP2',name:'JPEG 2000'},
    {ext:'J2K',name:'JPEG 2000 Code Stream'},{ext:'HDR',name:'High Dynamic Range'},{ext:'EXR',name:'OpenEXR HDR'},
    {ext:'WBMP',name:'Wireless Bitmap'},{ext:'FLIF',name:'Free Lossless Image Format'},
    {ext:'PNM',name:'Portable Any Map'},{ext:'PAM',name:'Portable Arbitrary Map'},{ext:'JXR',name:'JPEG XR'},
    {ext:'WDP',name:'Windows Media Photo'},{ext:'HDP',name:'HD Photo'},{ext:'JNG',name:'JPEG Network Graphics'},
    {ext:'MNG',name:'Multiple Network Graphics'},{ext:'DIB',name:'Device Independent Bitmap'},
    {ext:'DCX',name:'Multi-page PCX'},{ext:'PICT',name:'Apple PICT Format'},
    {ext:'SGI',name:'Silicon Graphics Image'},{ext:'SUN',name:'Sun Raster Image'}
  ]},
  { id:'video', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="23 7 16 12 23 17 23 7"/><rect x="1" y="5" width="15" height="14" rx="2"/></svg>`, name:'Video', formats:[
    {ext:'MP4',name:'MPEG-4 Video'},{ext:'MOV',name:'Apple QuickTime Movie'},{ext:'AVI',name:'Audio Video Interleave'},
    {ext:'MKV',name:'Matroska Video'},{ext:'WEBM',name:'WebM Video'},{ext:'FLV',name:'Flash Video'},
    {ext:'WMV',name:'Windows Media Video'},{ext:'M4V',name:'iTunes Video File'},{ext:'OGV',name:'Ogg Video'},
    {ext:'3GP',name:'3GPP Mobile Video'},{ext:'3G2',name:'3GPP2 Mobile Video'},{ext:'MPG',name:'MPEG-1/2 Video'},
    {ext:'MPEG',name:'MPEG Video'},{ext:'M2V',name:'MPEG-2 Video'},{ext:'VOB',name:'DVD Video Object'},
    {ext:'TS',name:'MPEG Transport Stream'},{ext:'MTS',name:'AVCHD Video'},{ext:'M2TS',name:'Blu-ray Video'},
    {ext:'DV',name:'Digital Video'},{ext:'ASF',name:'Advanced Systems Format'},{ext:'RM',name:'RealMedia'},
    {ext:'RMVB',name:'RealMedia Variable Bitrate'},{ext:'F4V',name:'Flash MP4 Video'},{ext:'SWF',name:'ShockWave Flash'},
    {ext:'MXF',name:'Material Exchange Format'},{ext:'GXF',name:'General Exchange Format'},{ext:'H264',name:'H.264 Raw Video'},
    {ext:'H265',name:'H.265 / HEVC Raw'},{ext:'HEVC',name:'High Efficiency Video Coding'},{ext:'VP8',name:'VP8 Video'},
    {ext:'VP9',name:'VP9 Video'},{ext:'AV1',name:'AV1 Video Stream'},{ext:'DIVX',name:'DivX Video'},
    {ext:'XVID',name:'Xvid Video'},{ext:'OGX',name:'Ogg Multiplex'},{ext:'IVF',name:'Indeo Video Format'},
    {ext:'AMV',name:'AMV Video (MP4/MTV)'},{ext:'NSV',name:'Nullsoft Streaming Video'},{ext:'ROQ',name:'Quake ROQ Video'},
    {ext:'VCD',name:'Video CD'},{ext:'SVCD',name:'Super Video CD'},{ext:'M4B',name:'MPEG-4 Video Bookmark'},
    {ext:'M4R',name:'iTunes Ringtone Video'},{ext:'MJPEG',name:'Motion JPEG'},{ext:'MJP2',name:'Motion JPEG 2000'},
    {ext:'CAVS',name:'Chinese AVS Video'},{ext:'WTV',name:'Windows Recorded TV Show'},
    {ext:'DVR-MS',name:'Microsoft DVR Recording'},{ext:'VRO',name:'DVD Video Recording'},
    {ext:'STREAM',name:'Generic Media Stream'}
  ]},
  { id:'audio', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg>`, name:'Audio', formats:[
    {ext:'MP3',name:'MPEG Audio Layer III'},{ext:'WAV',name:'Waveform Audio File'},{ext:'FLAC',name:'Free Lossless Audio Codec'},
    {ext:'AAC',name:'Advanced Audio Coding'},{ext:'OGG',name:'Ogg Vorbis'},{ext:'M4A',name:'MPEG-4 Audio'},
    {ext:'AIFF',name:'Audio Interchange File Format'},{ext:'AIF',name:'Apple Audio Interchange'},{ext:'WMA',name:'Windows Media Audio'},
    {ext:'OPUS',name:'Opus Audio'},{ext:'AMR',name:'Adaptive Multi-Rate'},{ext:'AU',name:'Sun/NeXT Audio'},
    {ext:'RA',name:'RealAudio'},{ext:'MKA',name:'Matroska Audio'},{ext:'APE',name:"Monkey's Audio"},
    {ext:'WV',name:'WavPack'},{ext:'TTA',name:'True Audio'},{ext:'MPC',name:'Musepack'},
    {ext:'SPX',name:'Speex Audio'},{ext:'CAF',name:'Core Audio Format'},{ext:'DSF',name:'DSD Stream File'},
    {ext:'DFF',name:'DSDIFF Audio'},{ext:'AC3',name:'Dolby AC-3'},{ext:'EAC3',name:'Enhanced AC-3'},
    {ext:'DTS',name:'DTS Audio'},{ext:'MP2',name:'MPEG Audio Layer II'},{ext:'MP1',name:'MPEG Audio Layer I'},
    {ext:'M4B',name:'MPEG-4 Audiobook'},{ext:'MIDI',name:'Musical Instrument Digital Interface'},{ext:'MID',name:'MIDI File'},
    {ext:'XM',name:'Extended Module'},{ext:'MOD',name:'Module Audio'},{ext:'S3M',name:'ScreamTracker 3 Module'},
    {ext:'IT',name:'Impulse Tracker Module'},{ext:'669',name:'UNIS 669 Tracker'},{ext:'GSM',name:'GSM Audio'},
    {ext:'VOC',name:'Creative Voice File'},{ext:'8SVX',name:'8-Bit Sampled Voice'},
    {ext:'SND',name:'Sound File'},{ext:'SD2',name:'Sound Designer II'},{ext:'W64',name:'Sony Wave64'},
    {ext:'RF64',name:'Broadcast Wave 64-bit'},{ext:'BWF',name:'Broadcast Wave Format'},{ext:'ATRAC',name:'Sony ATRAC'},
    {ext:'QCP',name:'Qualcomm PureVoice'},{ext:'ADPCM',name:'Adaptive PCM Audio'},
    {ext:'ALAW',name:'A-law Companded Audio'},{ext:'ULAW',name:'μ-law Companded Audio'},
    {ext:'IFF',name:'Interchange File Format Audio'},{ext:'PVF',name:'Portable Voice Format'}
  ]},
  { id:'document', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>`, name:'Documents', formats:[
    {ext:'PDF',name:'Portable Document Format'},{ext:'DOCX',name:'Word Open XML Document'},{ext:'DOC',name:'Microsoft Word Document'},
    {ext:'ODT',name:'OpenDocument Text'},{ext:'RTF',name:'Rich Text Format'},{ext:'TXT',name:'Plain Text'},
    {ext:'HTML',name:'HyperText Markup Language'},{ext:'HTM',name:'HTML File'},{ext:'MD',name:'Markdown'},
    {ext:'TEX',name:'LaTeX Document'},{ext:'PAGES',name:'Apple Pages Document'},{ext:'WPD',name:'WordPerfect Document'},
    {ext:'WPS',name:'Works Word Processor'},{ext:'DOCM',name:'Word Macro-Enabled Document'},{ext:'DOTX',name:'Word Template'},
    {ext:'FODT',name:'Flat OpenDocument Text'},{ext:'OTT',name:'OpenDocument Text Template'},{ext:'SXW',name:'StarOffice Writer'},
    {ext:'ABW',name:'AbiWord Document'},{ext:'MCW',name:'MacWrite Document'},{ext:'XML',name:'XML Document'},
    {ext:'JSON',name:'JSON Data File'},{ext:'YAML',name:'YAML Data File'},{ext:'CSV',name:'Comma-Separated Values'},
    {ext:'TSV',name:'Tab-Separated Values'},{ext:'LOG',name:'Log File'},{ext:'NFO',name:'Info Text File'},
    {ext:'ASC',name:'ASCII Text'},{ext:'DIZ',name:'Description in ZIP'},{ext:'RST',name:'reStructuredText'},
    {ext:'DOCX',name:'Word Open XML Document'},{ext:'ODG',name:'OpenDocument Graphics'},{ext:'ODF',name:'OpenDocument Formula'},
    {ext:'XHTML',name:'Extensible HTML'},{ext:'MHT',name:'MIME HTML Archive'},{ext:'MHTML',name:'MIME Encapsulation of HTML'},
    {ext:'WRI',name:'Windows Write'},{ext:'SAM',name:'Ami Pro Document'},{ext:'LWPX',name:'Lotus Word Pro'},
    {ext:'SDW',name:'StarWriter Document'},{ext:'SXW',name:'StarOffice Writer Older'},{ext:'PDFA',name:'PDF/A Archival'},
    {ext:'PDFX',name:'PDF/X Print Exchange'},{ext:'PDFE',name:'PDF/E Engineering'},{ext:'FDF',name:'Forms Data Format'},
    {ext:'XFDF',name:'XML Forms Data Format'},{ext:'DJVU',name:'DjVu Document'},{ext:'EPUB',name:'EPUB Document'},
    {ext:'CBZ',name:'Comic Book ZIP'},{ext:'CBR',name:'Comic Book RAR'}
  ]},
  { id:'spreadsheet', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="18" height="18" rx="1"/><line x1="3" y1="9" x2="21" y2="9"/><line x1="3" y1="15" x2="21" y2="15"/><line x1="9" y1="3" x2="9" y2="21"/><line x1="15" y1="3" x2="15" y2="21"/></svg>`, name:'Spreadsheets', formats:[
    {ext:'XLSX',name:'Excel Open XML Spreadsheet'},{ext:'XLS',name:'Microsoft Excel 97-2003'},{ext:'CSV',name:'Comma-Separated Values'},
    {ext:'TSV',name:'Tab-Separated Values'},{ext:'ODS',name:'OpenDocument Spreadsheet'},{ext:'FODS',name:'Flat OpenDocument Spreadsheet'},
    {ext:'XLSM',name:'Excel Macro-Enabled Workbook'},{ext:'XLSB',name:'Excel Binary Workbook'},{ext:'XLTX',name:'Excel Template'},
    {ext:'XLTM',name:'Excel Macro-Enabled Template'},{ext:'XLR',name:'Works Spreadsheet'},{ext:'SXC',name:'StarOffice Calc'},
    {ext:'OTS',name:'OpenDocument Spreadsheet Template'},{ext:'DIF',name:'Data Interchange Format'},{ext:'SYLK',name:'Symbolic Link Format'},
    {ext:'NUMBERS',name:'Apple Numbers'},{ext:'WKS',name:'Lotus 1-2-3 Worksheet'},{ext:'WK1',name:'Lotus 1-2-3 v1'},
    {ext:'WK3',name:'Lotus 1-2-3 v3'},{ext:'WK4',name:'Lotus 1-2-3 v4'},{ext:'123',name:'Lotus 1-2-3'},
    {ext:'PARQUET',name:'Apache Parquet'},{ext:'FEATHER',name:'Apache Feather'},{ext:'HDF5',name:'Hierarchical Data Format'},
    {ext:'GNUMERIC',name:'Gnumeric Spreadsheet'},{ext:'WQ1',name:'Quattro Pro v1'},{ext:'WQ2',name:'Quattro Pro v2'},
    {ext:'QB',name:'Quattro Pro Spreadsheet'},{ext:'QPW',name:'Quattro Pro Workbook'},{ext:'SDC',name:'StarCalc Spreadsheet'},
    {ext:'SXC',name:'StarOffice Calc Older'},{ext:'ET',name:'WPS Spreadsheet'},{ext:'ETT',name:'WPS Spreadsheet Template'},
    {ext:'CELL',name:'Multiplan Spreadsheet'},{ext:'MOD',name:'Multiplan Module'},{ext:'GS',name:'Google Sheets Export'},
    {ext:'WB1',name:'Quattro Pro Notebook'},{ext:'WB2',name:'Quattro Pro Notebook v2'},{ext:'WB3',name:'Quattro Pro Notebook v3'},
    {ext:'XLW',name:'Excel Workspace'},{ext:'XLA',name:'Excel Add-In'},{ext:'XLAM',name:'Excel Open XML Add-In'},
    {ext:'XLTM',name:'Excel Macro Template'},{ext:'CSV',name:'CSV (semicolon)'},{ext:'PRN',name:'Formatted Text (Space Delimited)'},
    {ext:'DBF',name:'dBASE Data Table'},{ext:'WKS',name:'Works Spreadsheet'},{ext:'NUMBERS',name:'Apple Numbers Spreadsheet'},{ext:'GSHEET',name:'Google Sheet'},{ext:'DEXL',name:'DEX Spreadsheet'}
  ]},
  { id:'presentation', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="3" width="20" height="14" rx="2"/><line x1="8" y1="21" x2="16" y2="21"/><line x1="12" y1="17" x2="12" y2="21"/></svg>`, name:'Presentations', formats:[
    {ext:'PPTX',name:'PowerPoint Open XML'},{ext:'PPT',name:'Microsoft PowerPoint 97-2003'},{ext:'ODP',name:'OpenDocument Presentation'},
    {ext:'PPTM',name:'PowerPoint Macro-Enabled'},{ext:'PPSX',name:'PowerPoint Show'},{ext:'PPSM',name:'PowerPoint Macro Show'},
    {ext:'POTX',name:'PowerPoint Template'},{ext:'POTM',name:'PowerPoint Macro Template'},{ext:'KEY',name:'Apple Keynote'},
    {ext:'FODP',name:'Flat OpenDocument Presentation'},{ext:'SXI',name:'StarOffice Impress'},{ext:'OTP',name:'OpenDocument Presentation Template'},
    {ext:'PPS',name:'PowerPoint Slideshow (legacy)'},
    {ext:'POT',name:'PowerPoint Template (legacy)'},{ext:'PPTHTML',name:'PowerPoint HTML Export'},
    {ext:'SDD',name:'StarImpress Presentation'},{ext:'SXI',name:'StarOffice Impress Older'},
    {ext:'THMX',name:'Office Theme'},{ext:'PPAM',name:'PowerPoint Add-In'},
    {ext:'GSLIDES',name:'Google Slides Export'},{ext:'SWF',name:'Flash Presentation'},
    {ext:'HTML',name:'HTML Slideshow'},{ext:'PDF',name:'PDF Presentation'},
    {ext:'PNG',name:'PNG Slide Export'},{ext:'JPG',name:'JPEG Slide Export'},
    {ext:'GIF',name:'Animated GIF Slideshow'},{ext:'MP4',name:'MP4 Video Export'},
    {ext:'WEBM',name:'WebM Video Export'},{ext:'OGV',name:'OGV Video Export'},
    {ext:'SVG',name:'SVG Slide Export'},{ext:'TIFF',name:'TIFF Slide Export'},
    {ext:'BMP',name:'BMP Slide Export'},{ext:'EMF',name:'Enhanced Metafile'},
    {ext:'WMF',name:'Windows Metafile'},{ext:'SHOW',name:'Slide Show File'},
    {ext:'NB',name:'Mathematica Notebook'},{ext:'DPS',name:'WPS Presentation'},
    {ext:'DPT',name:'WPS Presentation Template'},{ext:'PRZ',name:'Freelance Graphics'},
    {ext:'SHW',name:'Corel Presentations'},{ext:'CGM',name:'Computer Graphics Metafile'},
    {ext:'HMD',name:'HanShow Presentation'},{ext:'HMT',name:'HanShow Template'},
    {ext:'IMPRESS',name:'LibreOffice Impress'},{ext:'ODGX',name:'Extended ODP'},
    {ext:'PPTM2',name:'PowerPoint Macro Show'},{ext:'PPSX2',name:'PowerPoint Show v2'},
    {ext:'PPTX2',name:'PowerPoint v2 Export'},{ext:'ODP2',name:'OpenDocument Presentation v2'},{ext:'IMPRESS2',name:'LibreOffice Impress v2'}
  ]},
  { id:'ebook', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>`, name:'eBooks', formats:[
    {ext:'EPUB',name:'Electronic Publication'},{ext:'MOBI',name:'Mobipocket eBook'},{ext:'AZW',name:'Amazon Kindle Format'},
    {ext:'AZW3',name:'Amazon Kindle Format 8'},{ext:'KFX',name:'Kindle Format X'},{ext:'FB2',name:'FictionBook 2'},
    {ext:'LIT',name:'Microsoft Reader'},{ext:'LRF',name:'BroadBand eBook'},{ext:'PDB',name:'Palm Database eBook'},
    {ext:'DJVU',name:'DjVu Document'},{ext:'CBZ',name:'Comic Book ZIP'},{ext:'CBR',name:'Comic Book RAR'},
    {ext:'CB7',name:'Comic Book 7-Zip'},{ext:'CBT',name:'Comic Book TAR'},{ext:'CHM',name:'Compiled HTML Help'},
    {ext:'HTMLZ',name:'Zipped HTML eBook'},{ext:'SNB',name:'Shanda Bambook'},{ext:'TCR',name:'Psion eBook'},
    {ext:'TXTZ',name:'Zipped TXT eBook'},{ext:'PRC',name:'Palm Resource Code'},{ext:'OEB',name:'Open eBook'},
    {ext:'OPF',name:'Open Packaging Format'},{ext:'IBOOKS',name:'Apple iBooks'},
    {ext:'EPUB2',name:'EPUB 2 Format'},{ext:'EPUB3',name:'EPUB 3 Format'},{ext:'KEPUB',name:'Kobo EPUB'},
    {ext:'ACSM',name:'Adobe Content Server'},{ext:'LPF',name:'Lightweight Packaging Format'},
    {ext:'BRF',name:'Braille Ready File'},{ext:'PEF',name:'Portable Embosser Format'},
    {ext:'NCX',name:'Navigation Control XML'},{ext:'DAISY',name:'DAISY Talking Book'},
    {ext:'DTB',name:'Digital Talking Book'},{ext:'SMIL',name:'Synchronized Multimedia'},
    {ext:'ZTX',name:'Zipped Text eBook'},{ext:'PLKR',name:'Plucker eBook'},
    {ext:'OEB2',name:'Open eBook v2'},{ext:'NLM',name:'National Library Medicine'},
    {ext:'WOLF',name:'Wolfram Notebook'},{ext:'RB',name:'Rocket eBook'},
    {ext:'TCR',name:'Psion eBook'},{ext:'SNB',name:'Shanda Bambook'},
    {ext:'TR2',name:'TomeRaider v2'},{ext:'TR3',name:'TomeRaider v3'},
    {ext:'PDOC',name:'PalmDOC Alias'},{ext:'COMIC',name:'Generic Comic Format'},{ext:'AZW4',name:'Kindle Topaz'},{ext:'AZW5',name:'Kindle Format 5'},{ext:'IMP',name:'Imptiko eBook'},{ext:'LIT2',name:'MS Reader v2'}
  ]},
  { id:'archive', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="21 8 21 21 3 21 3 8"/><rect x="1" y="3" width="22" height="5"/><line x1="10" y1="12" x2="14" y2="12"/></svg>`, name:'Archives', formats:[
    {ext:'ZIP',name:'ZIP Archive'},{ext:'RAR',name:'Roshal Archive'},{ext:'7Z',name:'7-Zip Archive'},
    {ext:'TAR',name:'Tape Archive'},{ext:'GZ',name:'Gzip Compressed'},{ext:'BZ2',name:'Bzip2 Compressed'},
    {ext:'XZ',name:'XZ Compressed'},{ext:'TGZ',name:'Tar + Gzip'},{ext:'LZMA',name:'LZMA Compressed'},
    {ext:'LZ',name:'Lzip Archive'},{ext:'LZ4',name:'LZ4 Compressed'},{ext:'ZSTD',name:'Zstandard'},
    {ext:'ZST',name:'Zstandard Compressed'},{ext:'CAB',name:'Windows Cabinet'},{ext:'ISO',name:'Disk Image ISO'},
    {ext:'DMG',name:'macOS Disk Image'},{ext:'IMG',name:'Raw Disk Image'},{ext:'WIM',name:'Windows Imaging Format'},
    {ext:'ESD',name:'Electronic Software Download'},{ext:'ARJ',name:'ARJ Archive'},{ext:'ACE',name:'ACE Archive'},
    {ext:'LZH',name:'LZH Archive'},{ext:'LHA',name:'LHA Archive'},{ext:'ARC',name:'ARC Archive'},
    {ext:'ZOO',name:'ZOO Archive'},{ext:'PAK',name:'PAK Archive'},{ext:'PKZ',name:'PKZIP Archive'},
    {ext:'TAR.GZ',name:'Gzipped Tar'},{ext:'TAR.BZ2',name:'Bzipped Tar'},{ext:'TAR.XZ',name:'XZ Tar'},
    {ext:'CPIO',name:'CPIO Archive'},{ext:'SHAR',name:'Shell Archive'},{ext:'XAR',name:'Extensible Archive'},
    {ext:'DAR',name:'Disk ARchive'},{ext:'KGB',name:'KGB Archiver'},{ext:'ZPAQ',name:'ZPAQ Archive'},
    {ext:'PEA',name:'PEA Archive'},{ext:'SQUASHFS',name:'SquashFS Image'},{ext:'BROTLI',name:'Brotli Compressed'},
    {ext:'SNAP',name:'Linux Snap Package'},{ext:'DEB',name:'Debian Package'},{ext:'RPM',name:'RPM Package'},
    {ext:'PKG',name:'macOS Installer'},{ext:'MSI',name:'Windows Installer'},{ext:'APPIMAGE',name:'Linux AppImage'},
    {ext:'VSIX',name:'VS Code Extension'},{ext:'XPI',name:'Firefox Extension'},{ext:'NUPKG',name:'NuGet Package'},{ext:'EGG',name:'Python Egg'},{ext:'WHEEL',name:'Python Wheel'}
  ]},
  { id:'3d', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2L2 7l10 5 10-5-10-5z"/><path d="M2 17l10 5 10-5"/><path d="M2 12l10 5 10-5"/></svg>`, name:'3D Models', formats:[
    {ext:'OBJ',name:'Wavefront OBJ'},{ext:'STL',name:'Stereolithography'},{ext:'FBX',name:'Autodesk FBX'},
    {ext:'GLTF',name:'GL Transmission Format'},{ext:'GLB',name:'Binary glTF'},{ext:'DAE',name:'Collada'},
    {ext:'3DS',name:'3D Studio'},{ext:'PLY',name:'Polygon File Format'},{ext:'OFF',name:'Object File Format'},
    {ext:'X3D',name:'Extensible 3D'},{ext:'VRML',name:'Virtual Reality Modeling Language'},{ext:'WRL',name:'VRML World'},
    {ext:'AMF',name:'Additive Manufacturing Format'},{ext:'3MF',name:'3D Manufacturing Format'},{ext:'SKP',name:'SketchUp'},
    {ext:'BLEND',name:'Blender File'},{ext:'MAX',name:'3ds Max Scene'},{ext:'MA',name:'Maya ASCII'},
    {ext:'MB',name:'Maya Binary'},{ext:'C4D',name:'Cinema 4D'},{ext:'LWS',name:'LightWave Scene'},
    {ext:'LWO',name:'LightWave Object'},{ext:'IFC',name:'Industry Foundation Classes'},{ext:'U3D',name:'Universal 3D'},
    {ext:'STEP',name:'Standard for Exchange of Product data'},{ext:'STP',name:'STEP File'},{ext:'IGES',name:'Initial Graphics Exchange'},
    {ext:'IGS',name:'IGES File'},{ext:'JT',name:'Jupiter Tessellation'},{ext:'3DM',name:'Rhino 3D Model'},
    {ext:'USDA',name:'USD ASCII'},{ext:'USDC',name:'USD Crate'},{ext:'USDZ',name:'USD Zip'},
    {ext:'ABC',name:'Alembic'},{ext:'BVH',name:'BioVision Hierarchy'},{ext:'MDD',name:'Point Cache'},
    {ext:'PC2',name:'Point Cache v2'},{ext:'VDB',name:'OpenVDB Volume'},{ext:'VTK',name:'VTK Dataset'},
    {ext:'MSH',name:'Gmsh Mesh'},{ext:'MESH',name:'Generic Mesh'},{ext:'TRI',name:'Triangle Mesh'},
    {ext:'G',name:'BRL-CAD Geometry'},{ext:'ASC2',name:'Point Cloud ASCII'},{ext:'BREP',name:'Boundary Representation'},{ext:'PTS',name:'3D Point Cloud'},{ext:'E57',name:'3D Imaging Exchange'},{ext:'POV',name:'POV-Ray Scene'},{ext:'SCN',name:'Generic Scene'},{ext:'SCNX',name:'Scene Extended'}
  ]},
  { id:'cad', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>`, name:'CAD / Vector', formats:[
    {ext:'DWG',name:'AutoCAD Drawing'},{ext:'DXF',name:'Drawing Exchange Format'},{ext:'DWF',name:'Design Web Format'},
    {ext:'DWT',name:'AutoCAD Template'},{ext:'DWS',name:'AutoCAD Standards'},{ext:'SVG',name:'Scalable Vector Graphics'},
    {ext:'AI',name:'Adobe Illustrator'},{ext:'EPS',name:'Encapsulated PostScript'},{ext:'CDR',name:'CorelDRAW'},
    {ext:'CMX',name:'Corel Presentation Exchange'},{ext:'VSD',name:'Visio Drawing'},{ext:'VSDX',name:'Visio Open XML Drawing'},
    {ext:'VSDM',name:'Visio Macro-Enabled Drawing'},{ext:'EMF',name:'Enhanced Metafile'},{ext:'WMF',name:'Windows Metafile'},
    {ext:'CGM',name:'Computer Graphics Metafile'},{ext:'PCT',name:'PICT Format'},{ext:'XPS',name:'XML Paper Specification'},
    {ext:'OXPS',name:'Open XPS'},{ext:'SLDPRT',name:'SolidWorks Part'},{ext:'SLDASM',name:'SolidWorks Assembly'},
    {ext:'CATPART',name:'CATIA Part'},{ext:'CATPRODUCT',name:'CATIA Product'},{ext:'PRT',name:'Pro/E Creo Part'},
    {ext:'PDF',name:'PDF (vector)'},{ext:'AFDESIGN',name:'Affinity Designer'},{ext:'AFPHOTO',name:'Affinity Photo'},
    {ext:'SKETCH',name:'Sketch File'},{ext:'FIG',name:'Figma File'},{ext:'XD',name:'Adobe XD'},
    {ext:'SLDDRW',name:'SolidWorks Drawing'},{ext:'IPT',name:'Autodesk Inventor Part'},
    {ext:'IAM',name:'Autodesk Inventor Assembly'},{ext:'IDW',name:'Autodesk Inventor Drawing'},
    {ext:'DWG2',name:'AutoCAD 2D Drawing'},{ext:'DWGX',name:'AutoCAD Extended'},
    {ext:'RVT',name:'Revit Project'},{ext:'RFA',name:'Revit Family'},{ext:'RTE',name:'Revit Template'},
    {ext:'NWD',name:'Navisworks Document'},{ext:'NWC',name:'Navisworks Cache'},
    {ext:'3DM2',name:'Rhino 3D v2'},{ext:'FORM',name:'Form File'},{ext:'CREO',name:'PTC Creo File'},
    {ext:'PROE',name:'Pro/Engineer File'},{ext:'PAR',name:'Solid Edge Part'},{ext:'PSM',name:'Solid Edge Sheet Metal'},{ext:'ASM',name:'Solid Edge Assembly'},{ext:'PWD',name:'Solid Edge Weldment'},{ext:'CATDRAWING',name:'CATIA Drawing File'}
  ]},
  { id:'font', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" y1="20" x2="15" y2="20"/><line x1="12" y1="4" x2="12" y2="20"/></svg>`, name:'Fonts', formats:[
    {ext:'TTF',name:'TrueType Font'},{ext:'OTF',name:'OpenType Font'},{ext:'WOFF',name:'Web Open Font Format'},
    {ext:'WOFF2',name:'Web Open Font Format 2'},{ext:'EOT',name:'Embedded OpenType'},{ext:'PFA',name:'PostScript Font ASCII'},
    {ext:'PFB',name:'PostScript Font Binary'},{ext:'AFM',name:'Adobe Font Metrics'},{ext:'BDF',name:'Bitmap Distribution Format'},
    {ext:'PCF',name:'Portable Compiled Format'},{ext:'FNT',name:'Windows Font'},{ext:'FON',name:'Windows Font Resource'},
    {ext:'SVG',name:'SVG Font'},{ext:'PFM',name:'Printer Font Metrics'},{ext:'TTC',name:'TrueType Collection'},
    {ext:'DFONT',name:'Mac Data Fork Font'},{ext:'SFD',name:'FontForge Source Font'},
    {ext:'UFO',name:'Unified Font Object'},{ext:'VFB',name:'FontLab Studio Font'},{ext:'FOG',name:'Fontographer Font'},
    {ext:'GLYPHS',name:'Glyphs App Font'},{ext:'GLYPHSX',name:'Glyphs App Package'},{ext:'FEA',name:'OpenType Feature File'},
    {ext:'DESIGNSPACE',name:'Designspace File'},{ext:'KERX',name:'Extended Kerning Table'},
    {ext:'GSUB',name:'Glyph Substitution Table'},{ext:'GPOS',name:'Glyph Positioning Table'},
    {ext:'CFF',name:'Compact Font Format'},{ext:'CFF2',name:'Compact Font Format 2'},
    {ext:'T42',name:'Type 42 Font'},{ext:'T1',name:'Type 1 PostScript Font'},
    {ext:'MM',name:'Multiple Master Font'},{ext:'SNF',name:'Server Normal Format'},
    {ext:'FNT2',name:'Windows Font v2'},{ext:'FON2',name:'Windows Font Resource v2'},
    {ext:'TTCF',name:'TrueType Collection Font'},{ext:'WOFF3',name:'Web Font Format 3 (proposed)'},
    {ext:'VARFONT',name:'Variable Font'},{ext:'COL',name:'Color Font'},{ext:'SBIX',name:'Strike-Based Image Index'},
    {ext:'CBDT',name:'Color Bitmap Data Table'},{ext:'EBDT',name:'Embedded Bitmap Data'},
    {ext:'EBLC',name:'Embedded Bitmap Location'},{ext:'GDEF',name:'Glyph Definition Table'},
    {ext:'MATH',name:'Math Table Font'},{ext:'HVAR',name:'Horizontal Metrics Variation'},
    {ext:'MVAR',name:'Metrics Variation Table'},{ext:'STAT',name:'Style Attributes Table'},{ext:'AVAR',name:'Axis Variations Table'},{ext:'FVAR',name:'Font Variations Table'}
  ]},
  { id:'database', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg>`, name:'Database', formats:[
    {ext:'SQL',name:'Structured Query Language'},{ext:'SQLITE',name:'SQLite Database'},{ext:'DB',name:'Database File'},
    {ext:'MDB',name:'Microsoft Access Database'},{ext:'ACCDB',name:'Access Database'},{ext:'DBF',name:'dBASE Database'},
    {ext:'CSV',name:'CSV Export'},{ext:'JSON',name:'JSON Export'},{ext:'XML',name:'XML Export'},
    {ext:'XLSX',name:'Excel Export'},{ext:'DUMP',name:'Database Dump'},{ext:'BAK',name:'Database Backup'},
    {ext:'FDB',name:'Firebird Database'},{ext:'GDB',name:'Interbase Database'},{ext:'NSF',name:'Lotus Notes Database'},
    {ext:'ODB',name:'OpenDocument Database'},{ext:'PGDUMP',name:'PostgreSQL Dump'},{ext:'MYSQLDUMP',name:'MySQL Dump'},
    {ext:'MDF',name:'SQL Server Database'},{ext:'NDF',name:'SQL Server Secondary'},{ext:'LDF',name:'SQL Server Log'},
    {ext:'BSON',name:'Binary JSON'},{ext:'MSGPACK',name:'MessagePack'},{ext:'PARQUET',name:'Apache Parquet'},
    {ext:'SQLITE3',name:'SQLite3 Database'},{ext:'DB3',name:'SQLite3 Alias'},{ext:'REALM',name:'Realm Mobile Database'},
    {ext:'H2',name:'H2 Database'},{ext:'HSQLDB',name:'HyperSQL Database'},{ext:'DERBY',name:'Apache Derby Database'},
    {ext:'FRMO',name:'MySQL Table Format'},{ext:'MYD',name:'MySQL Data File'},{ext:'MYI',name:'MySQL Index File'},
    {ext:'IBD',name:'InnoDB Data File'},{ext:'FRM',name:'MySQL Table Definition'},{ext:'PDB',name:'Palm Database'},
    {ext:'DBX',name:'Outlook Express DB'},{ext:'WDB',name:'Works Database'},{ext:'FP7',name:'FileMaker Pro 7'},
    {ext:'FMP12',name:'FileMaker Pro 12'},{ext:'FP5',name:'FileMaker Pro 5'},{ext:'FPT',name:'FileMaker Memo'},
    {ext:'ADT',name:'Sybase DB'},{ext:'ADF',name:'ADF Database'},{ext:'RPDB',name:'Rekordbox Database'},
    {ext:'DTA',name:'Stata Data'},{ext:'SAS7BDAT',name:'SAS Data Set'},{ext:'XPT',name:'SAS Transport File'},{ext:'ARFF',name:'WEKA Attribute Format'},{ext:'LIBSVM',name:'LibSVM Data Format'}
  ]},
  { id:'code', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>`, name:'Code / Markup', formats:[
    {ext:'HTML',name:'HyperText Markup Language'},{ext:'CSS',name:'Cascading Style Sheets'},{ext:'JS',name:'JavaScript'},
    {ext:'TS',name:'TypeScript'},{ext:'JSX',name:'React JSX'},{ext:'TSX',name:'React TSX'},{ext:'VUE',name:'Vue Component'},
    {ext:'SVELTE',name:'Svelte Component'},{ext:'JSON',name:'JSON'},{ext:'XML',name:'XML'},{ext:'YAML',name:'YAML'},
    {ext:'TOML',name:'TOML Config'},{ext:'INI',name:'INI Config'},{ext:'ENV',name:'Environment Variables'},
    {ext:'PY',name:'Python'},{ext:'RB',name:'Ruby'},{ext:'PHP',name:'PHP'},{ext:'JAVA',name:'Java'},
    {ext:'C',name:'C Source'},{ext:'CPP',name:'C++ Source'},{ext:'H',name:'C/C++ Header'},{ext:'CS',name:'C#'},
    {ext:'GO',name:'Go'},{ext:'RS',name:'Rust'},{ext:'SWIFT',name:'Swift'},{ext:'KT',name:'Kotlin'},
    {ext:'DART',name:'Dart'},{ext:'R',name:'R Language'},{ext:'SCALA',name:'Scala'},{ext:'GROOVY',name:'Groovy'},
    {ext:'PERL',name:'Perl'},{ext:'LUA',name:'Lua'},{ext:'HASKELL',name:'Haskell'},{ext:'HS',name:'Haskell Source'},
    {ext:'ERLANG',name:'Erlang'},{ext:'ERL',name:'Erlang Source'},{ext:'CLOJURE',name:'Clojure'},{ext:'CLJ',name:'Clojure Source'},
    {ext:'SH',name:'Shell Script'},{ext:'BASH',name:'Bash Script'},{ext:'ZSH',name:'Zsh Script'},
    {ext:'PS1',name:'PowerShell'},{ext:'BAT',name:'Batch File'},{ext:'CMD',name:'Command File'},
    {ext:'MD',name:'Markdown'},{ext:'RST',name:'reStructuredText'},{ext:'TEX',name:'LaTeX'},{ext:'SQL',name:'SQL'},{ext:'WASM',name:'WebAssembly Text'},{ext:'WAT',name:'WebAssembly Text Format'}
  ]},
  { id:'email', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>`, name:'Email', formats:[
    {ext:'EML',name:'Email Message'},{ext:'MSG',name:'Outlook Message'},{ext:'PST',name:'Outlook Personal Storage'},
    {ext:'OST',name:'Outlook Offline Storage'},{ext:'MBOX',name:'Mailbox Format'},{ext:'MBX',name:'Mailbox'},
    {ext:'DBX',name:'Outlook Express Database'},{ext:'OLM',name:'Outlook for Mac'},{ext:'EMLX',name:'Apple Mail Message'},
    {ext:'NSF',name:'Lotus Notes Mail'},{ext:'VCF',name:'vCard'},{ext:'ICS',name:'iCalendar'},
    {ext:'ICAL',name:'iCalendar File'},{ext:'VCARD',name:'Virtual Contact Card'},{ext:'LDIF',name:'LDAP Data Interchange Format'},
    {ext:'RFC822',name:'RFC 822 Email'},{ext:'MH',name:'MH Mail Format'},{ext:'BABYL',name:'Babyl Mail Format'},
    {ext:'MMDF',name:'MMDF Mailbox'},{ext:'P7M',name:'S/MIME Encrypted'},{ext:'P7S',name:'S/MIME Signed'},
    {ext:'P7C',name:'S/MIME Certificate'},{ext:'PFX',name:'PKCS#12 Certificate'},{ext:'P12',name:'PKCS#12 Keystore'},
    {ext:'CER',name:'Certificate File'},{ext:'DER',name:'DER Certificate'},{ext:'PEM',name:'PEM Certificate'},
    {ext:'TNEF',name:'Transport Neutral Encapsulation'},{ext:'WINMAIL',name:'Winmail.dat'},
    {ext:'OFT',name:'Outlook Form Template'},{ext:'NWS',name:'Outlook Newsgroup Message'},
    {ext:'EDB',name:'Exchange Database'},{ext:'STM',name:'Exchange Streaming Media'},
    {ext:'VCF2',name:'vCard 2.1'},{ext:'VCF3',name:'vCard 3.0'},{ext:'VCF4',name:'vCard 4.0'},
    {ext:'VCALENDAR',name:'vCalendar'},{ext:'ICAL2',name:'iCalendar v2'},{ext:'IFB',name:'iCal Free Busy'},
    {ext:'VCARD2',name:'vCard Alternative'},{ext:'CONTACT2',name:'Windows Contact v2'},
    {ext:'GROUP',name:'Windows Contact Group'},{ext:'PST2',name:'PST Variant'},
    {ext:'MBOX2',name:'MBOX Variant'},{ext:'EMLX2',name:'Apple Mail Variant'},
    {ext:'OLKEMAILMESSAGE',name:'Outlook Mac Message'},{ext:'OLKCONTACT',name:'Outlook Mac Contact'},
    {ext:'OLKTASK',name:'Outlook Mac Task'},{ext:'OLKNOTE',name:'Outlook Mac Note'},
    {ext:'OLKEVENT',name:'Outlook Mac Event'}
  ]},
  { id:'subtitle', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="M7 15h4m5 0h-2M7 11h10"/></svg>`, name:'Subtitles', formats:[
    {ext:'SRT',name:'SubRip Text'},{ext:'ASS',name:'Advanced SubStation Alpha'},{ext:'SSA',name:'SubStation Alpha'},
    {ext:'VTT',name:'WebVTT Subtitles'},{ext:'SUB',name:'MicroDVD Subtitle'},{ext:'IDX',name:'DVD Subtitle Index'},
    {ext:'SBV',name:'YouTube Subtitles'},{ext:'LRC',name:'Lyric File'},{ext:'TXT',name:'Plain Text Subtitle'},
    {ext:'DFXP',name:'Distribution Format Exchange Profile'},{ext:'TTML',name:'Timed Text Markup Language'},
    {ext:'SMI',name:'SAMI Subtitle'},{ext:'SAMI',name:'Synchronized Accessible Media Interchange'},
    {ext:'SCC',name:'Scenarist Closed Caption'},{ext:'CAP',name:'Caption File'},{ext:'SBL',name:'Subtitle'},
    {ext:'STL',name:'Spruce Subtitle'},{ext:'QT',name:'QuickTime Text'},{ext:'RT',name:'RealText'},
    {ext:'VOBSUB',name:'DVD VOB Subtitle'},{ext:'PGS',name:'Presentation Graphic Stream'},
    {ext:'SUP',name:'Blu-ray SUP Subtitle'},{ext:'SST',name:'SubStation Title'},
    {ext:'USC',name:'USC Subtitle'},{ext:'AQT',name:'AQTitle Subtitle'},
    {ext:'JAS',name:'JACOSub Subtitle'},{ext:'RTS',name:'RealText Subtitle'},
    {ext:'MPSUB',name:'MPSub Subtitle'},{ext:'PJF',name:'PowerDivX Subtitle'},
    {ext:'TTAF',name:'Timed Text Author'},{ext:'YTT',name:'YouTube Timed Text'},
    {ext:'FCPXML',name:'Final Cut Pro XML'},{ext:'AVID',name:'Avid DS Caption'},
    {ext:'MCC',name:'MacCaption'},{ext:'N19',name:'NCI Caption'},
    {ext:'SON',name:'SON Subtitle'},{ext:'USF',name:'Universal Subtitle Format'},
    {ext:'WEBVTT',name:'WebVTT Extended'},{ext:'RT2',name:'RealText v2'},
    {ext:'CHCC',name:'Cheetah Caption'},{ext:'890',name:'890 Caption'},
    {ext:'SCENARIST',name:'Scenarist Format'},{ext:'SBDL',name:'SubDL Subtitle'},
    {ext:'TTML2',name:'TTML v2'},{ext:'IMSC',name:'IMSC Subtitle'},
    {ext:'EBU',name:'EBU N19 Subtitle'},{ext:'EBUTTD',name:'EBU-TT-D Subtitle'},
    {ext:'WDVTT',name:'WebVTT Draft'},{ext:'XMLSUBT',name:'XML Subtitle'},{ext:'SPRUCE',name:'Spruce Subtitle Format'}
  ]},
  { id:'gis', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 7l9-4 9 4v10l-9 4-9-4V7z"/><path d="M12 3v18"/><path d="M3 7l9 4 9-4"/></svg>`, name:'GIS / Maps', formats:[
    {ext:'SHP',name:'ESRI Shapefile'},{ext:'KML',name:'Keyhole Markup Language'},{ext:'KMZ',name:'Compressed KML'},
    {ext:'GPX',name:'GPS Exchange Format'},{ext:'GeoJSON',name:'GeoJSON'},{ext:'GeoTIFF',name:'Geographic TIFF'},
    {ext:'MIF',name:'MapInfo Interchange Format'},{ext:'MID',name:'MapInfo Data'},{ext:'TAB',name:'MapInfo TAB'},
    {ext:'GML',name:'Geography Markup Language'},{ext:'NTF',name:'National Transfer Format'},{ext:'E00',name:'ArcInfo Coverage'},
    {ext:'DEM',name:'Digital Elevation Model'},{ext:'OSM',name:'OpenStreetMap Data'},{ext:'GDB',name:'Esri File Geodatabase'},
    {ext:'SDF',name:'Spatial Data File'},{ext:'WKT',name:'Well-Known Text'},{ext:'WKB',name:'Well-Known Binary'},
    {ext:'CSV',name:'CSV with Coordinates'},{ext:'GEOJSON',name:'GeoJSON'},
    {ext:'TOPOJSON',name:'TopoJSON'},{ext:'GPKG',name:'GeoPackage DB'},{ext:'GPKGX',name:'GeoPackage Extended'},
    {ext:'LAS',name:'LiDAR Data Exchange'},{ext:'LAZ',name:'Compressed LiDAR'},{ext:'PCD',name:'Point Cloud Data'},
    {ext:'XYZ',name:'XYZ Point Cloud'},{ext:'PTS',name:'Point Cloud PTS'},{ext:'E57',name:'3D Imaging Data'},
    {ext:'S57',name:'IHO S-57 Chart'},{ext:'NC',name:'NetCDF'},{ext:'HDF',name:'Hierarchical Data Format'},
    {ext:'ECW',name:'Enhanced Compressed Wavelet'},{ext:'MRSID',name:'MrSID Raster'},{ext:'SID',name:'MrSID Image'},
    {ext:'NITF',name:'National Imagery'},{ext:'DTED',name:'Digital Terrain Elevation'},{ext:'BT',name:'Binary Terrain'},
    {ext:'TERRAIN',name:'Terrain File'},{ext:'IMG',name:'ERDAS Imagine'},{ext:'VRT',name:'GDAL Virtual'},
    {ext:'TOPO',name:'Topographic Data'},{ext:'CONTOUR',name:'Contour Data'},{ext:'GRID',name:'Generic Grid'},
    {ext:'RASTER',name:'Generic Raster'},{ext:'BAND',name:'Raster Band'},{ext:'WORLD',name:'World File'},
    {ext:'PRJ',name:'Projection File'},{ext:'SHX',name:'Shapefile Index'},{ext:'DBF2',name:'Shapefile Attributes'}
  ]},
  { id:'data', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>`, name:'Data / Config', formats:[
    {ext:'JSON',name:'JavaScript Object Notation'},{ext:'XML',name:'Extensible Markup Language'},{ext:'YAML',name:'YAML'},
    {ext:'TOML',name:'Tom\'s Obvious Minimal Language'},{ext:'CSV',name:'Comma-Separated Values'},{ext:'TSV',name:'Tab-Separated Values'},
    {ext:'INI',name:'Initialization File'},{ext:'ENV',name:'Environment Variables'},{ext:'PROPERTIES',name:'Java Properties'},
    {ext:'PLIST',name:'Property List'},{ext:'BSON',name:'Binary JSON'},{ext:'MSGPACK',name:'MessagePack'},
    {ext:'CBOR',name:'Concise Binary Object Representation'},{ext:'PROTOBUF',name:'Protocol Buffers'},{ext:'AVRO',name:'Apache Avro'},
    {ext:'PARQUET',name:'Apache Parquet'},{ext:'FEATHER',name:'Apache Feather'},{ext:'HDF5',name:'Hierarchical Data Format'},
    {ext:'NETCDF',name:'Network Common Data Form'},{ext:'MAT',name:'MATLAB Data'},{ext:'RDS',name:'R Data Store'},
    {ext:'PICKLE',name:'Python Pickle'},{ext:'NPZ',name:'NumPy Archive'},{ext:'NPY',name:'NumPy Array'},
    {ext:'JSONL',name:'JSON Lines'},{ext:'NDJSON',name:'Newline Delimited JSON'},{ext:'JSON5',name:'JSON5'},
    {ext:'HJSON',name:'Human JSON'},{ext:'CSON',name:'CoffeeScript Object Notation'},{ext:'RON',name:'Rusty Object Notation'},
    {ext:'DHALL',name:'Dhall Config'},{ext:'HOCON',name:'Human-Optimized Config'},
    {ext:'HCL',name:'HashiCorp Config Language'},{ext:'TFVARS',name:'Terraform Variables'},
    {ext:'JSONC',name:'JSON with Comments'},{ext:'JSONNET',name:'Jsonnet Template'},
    {ext:'CUE2',name:'CUE Language Config'},{ext:'BICEP',name:'Azure Bicep Template'},
    {ext:'DOTENV',name:'DotEnv File'},{ext:'EDITORCONFIG',name:'EditorConfig'},
    {ext:'GITCONFIG',name:'Git Config'},{ext:'NPMRC',name:'npm Config'},{ext:'YARNRC',name:'Yarn Config'},
    {ext:'PYPROJECT',name:'Python Project Config'},{ext:'CARGO',name:'Rust Cargo Config'},
    {ext:'GEMSPEC',name:'Ruby Gem Spec'},{ext:'PODFILE',name:'CocoaPods Podfile'},{ext:'GRADLE',name:'Gradle Build'},{ext:'BAZEL',name:'Bazel Build File'},{ext:'MAKEFILE',name:'GNU Makefile'}
  ]},
  { id:'misc', icon:`<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.07 4.93a10 10 0 0 1 0 14.14M4.93 4.93a10 10 0 0 0 0 14.14"/><path d="M15.54 8.46a5 5 0 0 1 0 7.07M8.46 8.46a5 5 0 0 0 0 7.07"/></svg>`, name:'Miscellaneous', formats:[
    {ext:'VHD',name:'Virtual Hard Disk'},{ext:'VMDK',name:'VMware Virtual Disk'},{ext:'OVA',name:'Open Virtualization Archive'},
    {ext:'QCOW2',name:'QEMU Copy On Write'},{ext:'NFO',name:'Info Text File'},{ext:'M3U',name:'Playlist'},
    {ext:'M3U8',name:'HLS Playlist'},{ext:'PLS',name:'Playlist File'},{ext:'XSPF',name:'XML Shareable Playlist'},
    {ext:'CUE',name:'Cue Sheet'},{ext:'DAT',name:'Generic Data File'},{ext:'BIN',name:'Binary File'},
    {ext:'HEX',name:'Hex Encoded File'},{ext:'BASE64',name:'Base64 Encoded'},{ext:'UUE',name:'UUEncoded File'},
    {ext:'TORRENT',name:'BitTorrent File'},{ext:'MAGNET',name:'Magnet Link'},{ext:'URL',name:'Internet Shortcut'},
    {ext:'WEBLOC',name:'macOS Web Shortcut'},{ext:'LNK',name:'Windows Shortcut'},{ext:'BASH_HISTORY',name:'Bash History'},
    {ext:'PREF',name:'Preferences File'},{ext:'REG',name:'Windows Registry File'},{ext:'INF',name:'Setup Info File'},
    {ext:'CRDOWNLOAD',name:'Chrome Download'},{ext:'PART',name:'Partial Download'},{ext:'TMP',name:'Temporary File'},
    {ext:'LOCK',name:'Lock File'},{ext:'PID',name:'Process ID File'},{ext:'SOCK',name:'Unix Socket'},
    {ext:'FIFO',name:'Named Pipe'},{ext:'ISO',name:'ISO Image (Misc)'},{ext:'NRG',name:'Nero Disc Image'},
    {ext:'MDS',name:'Media Descriptor'},{ext:'MDF',name:'Media Disc Image'},{ext:'CCD',name:'CloneCD Control'},
    {ext:'CUE2',name:'Disc Cue Sheet'},{ext:'GBI',name:'Ghost Boot Image'},{ext:'GHO',name:'Norton Ghost Image'},
    {ext:'SIS',name:'Symbian Install'},{ext:'SISX',name:'Symbian Install Extended'},{ext:'JAD',name:'Java Descriptor'},
    {ext:'JAR',name:'Java Archive'},{ext:'APK',name:'Android Package'},{ext:'IPA',name:'iOS App Package'},
    {ext:'APPX',name:'Windows App Package'},{ext:'MSIX',name:'Windows App Installer'},{ext:'XAP',name:'Silverlight App'},{ext:'WASM2',name:'WebAssembly Binary'},{ext:'MACHO',name:'Mach-O Executable'}
  ]}
];
